name: dispaset

dependencies:
  - python >= 3.8
  - future >= 0.15
  - click >= 3.3
  - numpy >= 1.10
  - scipy >= 0.15
  - matplotlib >= 1.5.1
  - pandas >= 0.19
  - xlrd = 1.2.0
  - xarray >= 0.11
  - netcdf4
  - pyyaml >= 5.1
  - pytest
  - networkx
  - cartopy >= 0.20
  - pip >= 9.0.1.
  - pip:
    - gdxcc
    - gamsxcc
    - optcc
    - setuptools_scm
    - pytest-cov
    - codecov